### PR TITLE
Build minified and bundled production version of component

### PR DESCRIPTION
**Pull request by stulees**
- Build now produces one production HTML file that inlines all dependency and component source JS/CSS/HTML
- Minifies all source of production HTML file
- Removes all comments from production HTML file
- Revised files to ignore for bower package
- Bump full version

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi @tejohnso Please review, thanks

**Comment by tejohnso** [comment]
@stulees can re remove the dist folder from the repo now?

**Comment by stulees** [comment]
@tejohnso Unfortunately no because if I git ignore it then it doesn't get included in the bower package for someone consuming this component.

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
