### PR TITLE
Add a public method that wraps the private one for getting metadata

### PR DESCRIPTION
**Pull request by donnapep**
Adding a public method for fetching metadata that is just a wrapper around the private one so that it can be called from Widgets.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep shouldn't we avoid to call metadata for single files also when the widget is loading or refreshing? cheers

**Comment by donnapep** [comment]
@rodrigopavezi There was actually no work to be done there. That logic has already been changed - https://github.com/Rise-Vision/rise-storage/blob/master/rise-storage.html#L1150.

**Comment by rodrigopavezi** [comment]
@donnapep that change is only covering when rise cache is running. The flow has also to change when rise cache is not running. For single file it should not request metadata when loading only if an error happens. More details of the flows are shown on the diagram of the Rise Cache brief document. cheers

**Comment by donnapep** [comment]
@rodrigopavezi What I'm finding confusing is the Trello card title and description. For example, the title is "Get file metadata from Rise Cache on failure". This implies that the card only needs to handle the case where RC is running. If that is not true, I think we either need to update the title and description of the card or create a new card.

**Comment by rodrigopavezi** [comment]
@donnapep makes sense, card added to the backlog https://trello.com/c/vGXp9g4f/1966-storage-component-refactor-single-file-flow-when-rise-cache-is-not-running. cheers

**Comment by donnapep** [comment]
@rodrigopavezi Thx! Is this one good to go?

**Comment by rodrigopavezi** [comment]
@donnapep I think it is better to change the function to call the subscription status check as I stated on the review above. cheers

**Comment by donnapep** [comment]
@rodrigopavezi Sorry, I don't see where you mentioned that. You mean that it should be calling `this._getStorageSubscription` instead of `_makeStorageRequest`? Thx.

**Comment by rodrigopavezi** [comment]
@donnapep strange, I opened a code review with a comment on this new review format. Anyway, that is right it should call the storage subscription as it is not going to come with the metadata anymore as we envisioned on the design. cheers

**Comment by donnapep** [comment]
@rodrigopavezi Weird. OK, I've updated the call. Please review again. Thx.

**Pull request merged**
