### PR TITLE
Base infrastructure and Rise Cache V2 ping

### PR DESCRIPTION
**Pull request by stulees**
- Base infrastructure and build files
- Ping Rise Cache V2 and handle response and error
- Unit tests

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍 I think we just have to make sure we reuse as much as possible from old component. We didn't even account for a rewrite of this component on the estimations. We account for changes to the old component. I see starting from scratch helps with validation. 
@donnapep FYI. cheers

**Comment by stulees** [comment]
@rodrigopavezi Agreed. Next tasks will likely require adding a lot of existing logic from old component, however it will also allow for some possible cleanup and refactoring that code too since we'll only add code that is required for validation.

**Comment by donnapep** [comment]
@stulees Is this one OK to be merged?

**Comment by stulees** [comment]
@donnapep Good to go

**Comment by rodrigopavezi** [comment]
@stulees agreed. cheers

**Comment by donnapep** [comment]
@stulees Thx!

**Pull request merged**
