### PR TITLE
Fixed the storage url for single file

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@donnapep @stulees I had to change the url for single files so the widget can load it. Please review. cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi What about if the file name has spaces and/or special characters in it?

**Comment by rodrigopavezi** [comment]
@stulees good catch. applied the encoding for the file path. Please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi Nice. Do you think it might be best to apply the same here - https://github.com/Rise-Vision/rise-storage/pull/11/files#diff-b11e354e371b5bda5971abab38fad364R1144

**Comment by rodrigopavezi** [comment]
@stulees yeap, I was thinking we could have a function for that right. I will add it. cheers

**Comment by rodrigopavezi** [comment]
@stulees changes made, please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi Looks good 👍

**Pull request merged**
